'\" t
.\"     Title: wolfpub-distributor-bill
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-DISTRIBUTOR\-BILL" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-distributor\-bill \- Generate a bill based on an order ID
.SH "SYNOPSIS"
.sp
\fBwolfpub distributor bill\fP \fIOrder ID\fP
.SH "DESCRIPTION"
.sp
Generate a bill based on an order ID
.SH "ARGUMENTS"
.sp
\fIOrder ID\fP
.RS 4
.RE