'\" t
.\"     Title: wolfpub-publish-deletesection
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PUBLISH\-DELETESECTION" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-publish\-deleteSection \- Delete a section from a chapter of a book edition
.SH "SYNOPSIS"
.sp
\fBwolfpub publish deleteSection\fP \fB\-c\fP=\fI<arg2>\fP \fB\-i\fP=\fI<arg0>\fP \fB\-s\fP=\fI<arg1>\fP
.SH "DESCRIPTION"
.sp
Delete a section from a chapter of a book edition
.SH "OPTIONS"
.sp
\fB\-c\fP, \fB\-cnumber\fP=\fI<arg2>\fP
.RS 4
The chapter number
.RE
.sp
\fB\-i\fP, \fB\-isbn\fP=\fI<arg0>\fP
.RS 4
The ISBN number of the edition
.RE
.sp
\fB\-s\fP, \fB\-snumber\fP=\fI<arg1>\fP
.RS 4
The section number
.RE