'\" t
.\"     Title: wolfpub-production-getbookbyattr
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PRODUCTION\-GETBOOKBYATTR" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-production\-getBookByAttr \- get book by attributes
.SH "SYNOPSIS"
.sp
\fBwolfpub production getBookByAttr\fP [\fB\-e\fP=\fI<arg3>\fP] [\fB\-pd\fP=\fI<arg1>\fP] [\fB\-pt\fP=\fI<arg4>\fP]
[\fB\-t\fP=\fI<arg2>\fP] \fIPublicationID\fP
.SH "DESCRIPTION"
.sp
get book by attributes
.SH "OPTIONS"
.sp
\fB\-e\fP, \fB\-editionNumber\fP=\fI<arg3>\fP
.RS 4
Edition Number
.RE
.sp
\fB\-pd, \-publicationDate\fP=\fI<arg1>\fP
.RS 4
Book Publication Date
.RE
.sp
\fB\-pt, \-PublicationTitle\fP=\fI<arg4>\fP
.RS 4
Publication Title
.RE
.sp
\fB\-t\fP, \fB\-publicationType\fP=\fI<arg2>\fP
.RS 4
Publication Type
.RE
.SH "ARGUMENTS"
.sp
\fIPublicationID\fP
.RS 4
.RE