'\" t
.\"     Title: wolfpub-production-track
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PRODUCTION\-TRACK" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-production\-track \- keep track of when each payment was claimed by its address
.SH "SYNOPSIS"
.sp
\fBwolfpub production track\fP [\fB\-a\fP=\fI<arg0>\fP] [\fB\-d\fP=\fI<arg1>\fP] \fISSN\fP \fIPaymentID\fP
.SH "DESCRIPTION"
.sp
keep track of when each payment was claimed by its address
.SH "OPTIONS"
.sp
\fB\-a\fP, \fB\-amount\fP=\fI<arg0>\fP
.RS 4
Payment Amount
.RE
.sp
\fB\-d\fP, \fB\-datePickedUp\fP=\fI<arg1>\fP
.RS 4
Date picked Up
.RE
.SH "ARGUMENTS"
.sp
\fISSN\fP, \fIPaymentID\fP
.RS 4
.RE