'\" t
.\"     Title: wolfpub-distributor-update
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-DISTRIBUTOR\-UPDATE" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-distributor\-update \- Update a distributor\(aqs information
.SH "SYNOPSIS"
.sp
\fBwolfpub distributor update\fP [\fB\-b\fP=\fI<arg4>\fP] [\fB\-c\fP=\fI<arg3>\fP] [\fB\-n\fP=\fI<arg0>\fP]
[\fB\-new_city\fP=\fI<arg7>\fP] [\fB\-new_street_addr\fP=\fI<arg6>\fP]
[\fB\-new_zip\fP=\fI<arg8>\fP] [\fB\-p\fP=\fI<arg2>\fP] [\fB\-s\fP=\fI<arg5>\fP]
[\fB\-t\fP=\fI<arg1>\fP] \fIStreet Address\fP \fICity\fP \fIZip\fP
.SH "DESCRIPTION"
.sp
Update a distributor\(cqs information
.SH "OPTIONS"
.sp
\fB\-b\fP, \fB\-balance\fP=\fI<arg4>\fP
.RS 4
Starting balance
.RE
.sp
\fB\-c\fP, \fB\-contact\fP=\fI<arg3>\fP
.RS 4
Contact name
.RE
.sp
\fB\-n\fP, \fB\-name\fP=\fI<arg0>\fP
.RS 4
Distributor name
.RE
.sp
\fB\-new_city\fP=\fI<arg7>\fP
.RS 4
New city
.RE
.sp
\fB\-new_street_addr\fP=\fI<arg6>\fP
.RS 4
New street address
.RE
.sp
\fB\-new_zip\fP=\fI<arg8>\fP
.RS 4
New zip
.RE
.sp
\fB\-p\fP, \fB\-phone\fP=\fI<arg2>\fP
.RS 4
Phone number
.RE
.sp
\fB\-s\fP, \fB\-state\fP=\fI<arg5>\fP
.RS 4
State
.RE
.sp
\fB\-t\fP, \fB\-type\fP=\fI<arg1>\fP
.RS 4
Distributor type
.RE
.SH "ARGUMENTS"
.sp
\fIStreet Address\fP, \fICity\fP, \fIZip\fP
.RS 4
.RE