'\" t
.\"     Title: wolfpub-report
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-REPORT" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-report \- Generate reports
.SH "SYNOPSIS"
.sp
\fBwolfpub report\fP [COMMAND]
.SH "DESCRIPTION"
.sp
Generate reports
.SH "COMMANDS"
.sp
\fBdistri_mon\fP
.RS 4
Generate monthly number and total price of each publication bought per distributor
.RE
.sp
\fBdistri_num\fP
.RS 4
Generate monthly total current number of distributors
.RE
.sp
\fBpay_time\fP
.RS 4
Generate total payments to editors and authors per time period
.RE
.sp
\fBpay_worktype\fP
.RS 4
Generate total payments to editors and authors per work type
.RE
.sp
\fBrev_city\fP
.RS 4
Generate total revenue per city since inception
.RE
.sp
\fBrev_distri\fP
.RS 4
Generate total revenue per distributor since inception
.RE
.sp
\fBrev_loc\fP
.RS 4
Generate total revenue per location since inception
.RE
.sp
\fBexpen\fP
.RS 4
Generate monthly total expenses
.RE
.sp
\fBrev\fP
.RS 4
Generate monthly total revenue of the publishing house
.RE