'\" t
.\"     Title: wolfpub-production-enteredition
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PRODUCTION\-ENTEREDITION" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-production\-enterEdition \- Enter information for a new book edition
.SH "SYNOPSIS"
.sp
\fBwolfpub production enterEdition\fP [\fB\-e\fP=\fI<arg1>\fP] [\fB\-ep\fP=\fI<arg3>\fP] \fB\-p\fP=\fI<arg0>\fP \fB\-pd\fP=\fI<arg2>\fP
\fIISBN\fP
.SH "DESCRIPTION"
.sp
Enter information for a new book edition
.SH "OPTIONS"
.sp
\fB\-e\fP, \fB\-editionNumber\fP=\fI<arg1>\fP
.RS 4
Book edition number
.RE
.sp
\fB\-ep, \-editionPrice\fP=\fI<arg3>\fP
.RS 4
Book new edition price
.RE
.sp
\fB\-p\fP, \fB\-PublicationID\fP=\fI<arg0>\fP
.RS 4
Book edition publicationID
.RE
.sp
\fB\-pd, \-publicationDate\fP=\fI<arg2>\fP
.RS 4
Book new edition publication date
.RE
.SH "ARGUMENTS"
.sp
\fIISBN\fP
.RS 4
.RE