'\" t
.\"     Title: wolfpub-report-pay_time
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-REPORT\-PAY_TIME" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-report\-pay_time \- Generate total payments to editors and authors per time period
.SH "SYNOPSIS"
.sp
\fBwolfpub report pay_time\fP
.SH "DESCRIPTION"
.sp
Generate total payments to editors and authors per time period