'\" t
.\"     Title: wolfpub-production-enterpayment
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PRODUCTION\-ENTERPAYMENT" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-production\-enterpayment \- enter payment of staff or invited employee
.SH "SYNOPSIS"
.sp
\fBwolfpub production enterpayment\fP [\fB\-c\fP=\fI<arg1>\fP] [\fB\-n\fP=\fI<arg0>\fP] [\fBp\fP=\fI<arg2>\fP] \fISSN\fP
.SH "DESCRIPTION"
.sp
enter payment of staff or invited employee
.SH "OPTIONS"
.sp
\fB\-c\fP, \fB\-contractPay\fP=\fI<arg1>\fP
.RS 4
Contract Pay
.RE
.sp
\fB\-n\fP, \fB\-name\fP=\fI<arg0>\fP
.RS 4
Employee name
.RE
.sp
\fBp, \-payPeriod\fP=\fI<arg2>\fP
.RS 4
Pay Period
.RE
.SH "ARGUMENTS"
.sp
\fISSN\fP
.RS 4
.RE