'\" t
.\"     Title: wolfpub-publish-addsection
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PUBLISH\-ADDSECTION" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-publish\-addSection \- Add a section to a chapter of a book edition
.SH "SYNOPSIS"
.sp
\fBwolfpub publish addSection\fP [\fB\-h\fP] \fB\-c\fP=\fI<arg4>\fP \fB\-i\fP=\fI<arg0>\fP \fB\-s\fP=\fI<arg3>\fP \fB\-t\fP=\fI<arg1>\fP
\fB\-w\fP=\fI<arg2>\fP
.SH "DESCRIPTION"
.sp
Add a section to a chapter of a book edition
.SH "OPTIONS"
.sp
\fB\-c\fP, \fB\-cnumber\fP=\fI<arg4>\fP
.RS 4
The chapter number
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Display a help message
.RE
.sp
\fB\-i\fP, \fB\-isbn\fP=\fI<arg0>\fP
.RS 4
The ISBN number of the edition
.RE
.sp
\fB\-s\fP, \fB\-snumber\fP=\fI<arg3>\fP
.RS 4
The section number
.RE
.sp
\fB\-t\fP, \fB\-title\fP=\fI<arg1>\fP
.RS 4
The title of the section
.RE
.sp
\fB\-w\fP, \fB\-text\fP=\fI<arg2>\fP
.RS 4
The text in the section
.RE