'\" t
.\"     Title: wolfpub-publish-deletearticle
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PUBLISH\-DELETEARTICLE" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-publish\-deleteArticle \- Delete article from a journal or a magazine issue
.SH "SYNOPSIS"
.sp
\fBwolfpub publish deleteArticle\fP [\fB\-h\fP] \fB\-d\fP=\fI<arg2>\fP \fB\-i\fP=\fI<arg1>\fP \fB\-t\fP=\fI<arg0>\fP
.SH "DESCRIPTION"
.sp
Delete article from a journal or a magazine issue
.SH "OPTIONS"
.sp
\fB\-d\fP, \fB\-date\fP=\fI<arg2>\fP
.RS 4
The publication date of the article
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.RS 4
Display a help message
.RE
.sp
\fB\-i\fP, \fB\-issn\fP=\fI<arg1>\fP
.RS 4
The ISSN of the publication
.RE
.sp
\fB\-t\fP, \fB\-title\fP=\fI<arg0>\fP
.RS 4
The title of the article
.RE