'\" t
.\"     Title: wolfpub-publish-assigneditornonbook
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PUBLISH\-ASSIGNEDITORNONBOOK" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-publish\-assignEditorNonBook \- Assign editors to a Book Edition
.SH "SYNOPSIS"
.sp
\fBwolfpub publish assignEditorNonBook\fP \fB\-d\fP=\fI<arg2>\fP \fB\-i\fP=\fI<arg1>\fP \fB\-s\fP=\fI<arg0>\fP
.SH "DESCRIPTION"
.sp
Assign editors to a Book Edition
.SH "OPTIONS"
.sp
\fB\-d\fP, \fB\-date\fP=\fI<arg2>\fP
.RS 4
The publication date of an isssue
.RE
.sp
\fB\-i\fP, \fB\-isbn\fP=\fI<arg1>\fP
.RS 4
The ISSN number of the journal or magazine
.RE
.sp
\fB\-s\fP, \fB\-ssn\fP=\fI<arg0>\fP
.RS 4
The Social Security Number of the editor
.RE