'\" t
.\"     Title: wolfpub-production-enterarticle
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PRODUCTION\-ENTERARTICLE" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-production\-enterArticle \- enter a article or enter article text into database
.SH "SYNOPSIS"
.sp
\fBwolfpub production enterArticle\fP \fB\-a\fP=\fI<arg0>\fP \fIPublicationID\fP \fIIssue Date\fP \fIArticle Title\fP
.SH "DESCRIPTION"
.sp
enter a article or enter article text into database
.SH "OPTIONS"
.sp
\fB\-a\fP, \fB\-articleText\fP=\fI<arg0>\fP
.RS 4
Article text
.RE
.SH "ARGUMENTS"
.sp
\fIPublicationID\fP, \fIIssue Date\fP, \fIArticle Title\fP
.RS 4
.RE