'\" t
.\"     Title: wolfpub-production-updatechapter
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PRODUCTION\-UPDATECHAPTER" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-production\-updateChapter \- update chapter
.SH "SYNOPSIS"
.sp
\fBwolfpub production updateChapter\fP \fB\-c\fP=\fI<arg0>\fP \fIISBN\fP \fIChapterNumber\fP
.SH "DESCRIPTION"
.sp
update chapter
.SH "OPTIONS"
.sp
\fB\-c\fP, \fB\-chapterTitle\fP=\fI<arg0>\fP
.RS 4
Chapter Title
.RE
.SH "ARGUMENTS"
.sp
\fIISBN\fP, \fIChapterNumber\fP
.RS 4
.RE