'\" t
.\"     Title: wolfpub-publish-addarticle
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PUBLISH\-ADDARTICLE" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-publish\-addArticle \- Add an article to a magazine or a journal issue
.SH "SYNOPSIS"
.sp
\fBwolfpub publish addArticle\fP \fB\-d\fP=\fI<arg3>\fP \fB\-i\fP=\fI<arg2>\fP \fB\-t\fP=\fI<arg0>\fP \fB\-w\fP=\fI<arg1>\fP \fB\-a\fP=\fI<arg4>\fP[,
\fI<arg4>\fP...] [\fB\-a\fP=\fI<arg4>\fP[,\fI<arg4>\fP...]]...
.SH "DESCRIPTION"
.sp
Add an article to a magazine or a journal issue
.SH "OPTIONS"
.sp
\fB\-a\fP, \fB\-ssn, \-author, \-authors\fP=\fI<arg4>\fP[,\fI<arg4>\fP...]
.RS 4
The Social Security Numbers of the authors of the article
.RE
.sp
\fB\-d\fP, \fB\-date\fP=\fI<arg3>\fP
.RS 4
The publication date of the issue
.RE
.sp
\fB\-i\fP, \fB\-issn\fP=\fI<arg2>\fP
.RS 4
The ISSN date of the publication
.RE
.sp
\fB\-t\fP, \fB\-title\fP=\fI<arg0>\fP
.RS 4
The title of the article
.RE
.sp
\fB\-w\fP, \fB\-text\fP=\fI<arg1>\fP
.RS 4
The text of the article
.RE