'\" t
.\"     Title: wolfpub-production-deleteedition
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 1.5.8
.\"      Date: 2020-04-13
.\"    Manual: Wolfpub Manual
.\"    Source: 
.\"  Language: English
.\"
.TH "WOLFPUB\-PRODUCTION\-DELETEEDITION" "1" "2020-04-13" "" "Wolfpub Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
wolfpub\-production\-deleteEdition \- Remove an book edition from the database
.SH "SYNOPSIS"
.sp
\fBwolfpub production deleteEdition\fP \fIPublicationID\fP \fIISBN\fP
.SH "DESCRIPTION"
.sp
Remove an book edition from the database
.SH "ARGUMENTS"
.sp
\fIPublicationID\fP, \fIISBN\fP
.RS 4
.RE