package entities;

import java.sql.Date;

public class Payment {
	/* Attributes
	 * 	PaymentID
	 * 	Amount
	 * 	DatePickedUp
	 */
	private String id;
	private Double amount;
	private java.sql.Date date;
	
	private Employee payee;

	public Payment(Employee payee) {
		super();
		this.payee = payee;
		/* TODO payment ID to be auto-generated by database */
	}

	public Payment(Double amount, Employee payee) {
		super();
		this.id = id;
		this.amount = amount;
		this.payee = payee;
	}

	public Payment(String id, Double amount, Date date, Employee payee) {
		super();
		this.id = id;
		this.amount = amount;
		this.date = date;
		this.payee = payee;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Double getAmount() {
		return amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public java.sql.Date getDate() {
		return date;
	}

	public void setDate(java.sql.Date date) {
		this.date = date;
	}

	public Employee getPayee() {
		return payee;
	}

	public void setPayee(Employee payee) {
		this.payee = payee;
	}	
}
